---
title: "dlookr: Data Diagnosis"
author: ""
always_allow_html: yes
output:
  dlookrExtra::dlookrExtra_templ_html:
    toc: true
---

```{r setup, echo=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      message = FALSE, 
                      warning = FALSE, 
                      collapse = FALSE,
                      comment = "#>",
                      fig.align = "center")
knitr::opts_chunk$set(fig.width = 12, fig.height = 9)
```

```{r load_packages}
library(dlookr)
library(dlookrExtra)
library(dplyr)
library(kableExtra)
library(reactable)
library(htmltools)
```

```{r import-data}
reportData <- get("reportData", .dlookrExtraEnv)

thres_uniq_cat <- $thres_uniq_cat$
thres_uniq_num <- $thres_uniq_num$  
```

```{css, echo=FALSE}
#header .title{
  color: $title_color$;
}

#header .navbar-wrapper {
  border-top: solid 1px $navbar$;
  border-bottom: solid 1px $navbar$;
}

.list-group-item.active, .list-group-item.active:hover, .list-group-item.active:focus {
    z-index: 2;
    color: #fff;
    background-color: $listgitem$;
    border-color: $listgitem$;
}

.nav-tabs>li.active>a, .nav-tabs>li.active>a:focus, .nav-tabs>li.active>a:hover {
    color: #555;
    cursor: default;
    background-color: #fff;
    border: 1px solid #ddd;
    border-bottom-color: transparent;
}

.nav-tabs>li>a {
    margin-right: 2px;
    line-height: 1.42857143;
    border: 1px solid transparent;
    border-radius: 4px 4px 0 0;
}

.nav>li>a {
    position: relative;
    display: block;
    padding: 10px 15px;
}

a {
    color: #337ab7 !important;
    text-decoration: none;
}

/* Warnings */
.tag {
  display: inline-block;
  padding: 2px 12px;
  border-radius: 5px;
  font-weight: 600;
  font-size: 12px;
}

.recommand-check {
  background: hsl(116, 60%, 90%);
  color: hsl(116, 30%, 25%);
}

.recommand-judgement {
  background: hsl(230, 70%, 90%);
  color: hsl(230, 45%, 30%);
}

.recommand-remove {
  background: hsl(350, 70%, 90%);
  color: hsl(350, 45%, 30%);
}
```

```{r diagose}
# Number of observations
N <- NROW(reportData)

# solve the overview
ov <- overview(reportData)

# diagnose the missing & unique
diagn_na_unique <- diagnose(reportData)

# diagnose the numeric
diagn_numeric <- diagnose_numeric(reportData)

tab_warning <- data.frame(
  warnings = character(500), status = character(500), variables = character(500),
  types = character(500), indicator = numeric(500), ratio = numeric(500), 
  recommand = character(500), stringsAsFactors = FALSE)

# duplicate --------------------------------------------------------------------
idx_last <- 0
n_duplicate <- length(attr(ov, "duplicate"))

if (n_duplicate > 0) {
  idx <- 1
  
  tab_warning$status[idx]    <- "duplicate"
  tab_warning$variables[idx] <- NA
  tab_warning$types[idx] <- NA  
  tab_warning$indicator[idx] <- n_duplicate
  tab_warning$ratio[idx]     <- n_duplicate / N
  tab_warning$warnings[idx]  <- sprintf(
    "dataset has %s (%s%%) duplicated observations", 
    format(n_duplicate, big.mark = ","),
    round(n_duplicate / N * 100, 1))
  tab_warning$recommand[idx]  <- "check"  
} else {
  idx <- NULL
}

# missing ----------------------------------------------------------------------
idx_last <- idx_last + length(idx)

warn_miss <- diagn_na_unique %>% 
  filter(missing_count > 0) %>% 
  select(variables, types, missing_count, missing_percent) %>% 
  arrange(desc(missing_count))

if (nrow(warn_miss) > 0) {
  idx <- seq(nrow(warn_miss)) + idx_last
  
  tab_warning$status[idx]    <- "missing"
  tab_warning$variables[idx] <- warn_miss$variables
  tab_warning$types[idx]     <- warn_miss$types  
  tab_warning$indicator[idx] <- warn_miss$missing_count
  tab_warning$ratio[idx]     <- warn_miss$missing_percent / 100
  tab_warning$warnings[idx]  <- sprintf(
    "%s has %s (%s%%) missing values", warn_miss$variables,
    format(warn_miss$missing_count, big.mark = ","),
    round(warn_miss$missing_percent, 1))
  tab_warning$recommand[idx]  <- "judgement"
} else {
  idx <- NULL
}

# cardinality: identifier ------------------------------------------------------
idx_last <- idx_last + length(idx)

warn_identifier <- diagn_na_unique %>% 
  filter(unique_rate == 1) %>% 
  select(variables, types, unique_count, unique_rate)

if (nrow(warn_identifier) > 0) {
  idx <- seq(nrow(warn_identifier)) + idx_last
  
  tab_warning$status[idx]     <- "cardinality"
  tab_warning$variables[idx]  <- warn_identifier$variables
  tab_warning$types[idx]      <- warn_identifier$types    
  tab_warning$indicator[idx]  <- warn_identifier$unique_count
  tab_warning$ratio[idx]      <- warn_identifier$unique_rate 
  tab_warning$warnings[idx]   <- sprintf(
    "%s has high(%.2f) cardinality, Maybe identifier",
    warn_identifier$variables, warn_identifier$unique_rate)
  tab_warning$recommand[idx]  <- "check"  
} else {
  idx <- NULL
}

# cardinality: constant --------------------------------------------------------
idx_last <- idx_last + length(idx)

warn_constant <- diagn_na_unique %>% 
  filter(unique_count == 1) %>% 
  select(variables, types, unique_count, unique_rate)

if (nrow(warn_constant) > 0) {
  idx <- seq(nrow(warn_constant)) + idx_last
  
  tab_warning$status[idx]     <- "cardinality"
  tab_warning$variables[idx]  <- warn_constant$variables
  tab_warning$types[idx]      <- warn_constant$types   
  tab_warning$indicator[idx]  <- warn_constant$unique_count
  tab_warning$ratio[idx]      <- warn_constant$unique_rate 
  tab_warning$warnings[idx]   <- sprintf(
    "%s has constant value \"%s\"",
    warn_constant$variables, 
    reportData[1, warn_constant$variables %>% as.character()] %>% 
      t() %>% 
      as.vector()
    )  
  tab_warning$recommand[idx]  <- "remove"
} else {
  idx <- NULL
}

# cardinally: high cardinality(category) ---------------------------------------
idx_last <- idx_last + length(idx)

warn_unique_cat <- diagn_na_unique %>% 
  filter(types %in% c("character", "factor", "ordered", "Date", "POSIXct")) %>%
  filter(unique_rate >= thres_uniq_cat & unique_rate < 1) %>%
  select(variables, types, unique_count, unique_rate)

if (nrow(warn_unique_cat) > 0) {
  idx <- seq(nrow(warn_unique_cat)) + idx_last
  
  tab_warning$status[idx]     <- "cardinality"
  tab_warning$variables[idx]  <- warn_unique_cat$variables
  tab_warning$types[idx]      <- warn_unique_cat$types   
  tab_warning$indicator[idx]  <- warn_unique_cat$unique_count
  tab_warning$ratio[idx]      <- warn_unique_cat$unique_rate 
  tab_warning$warnings[idx]   <- sprintf(
    "%s has a high cardinality. %s (%s%%) distinct values",
    warn_unique_cat$variables, 
    format(warn_unique_cat$unique_count, big.mark = ","),
    round(warn_unique_cat$unique_rate * 100, 1))  
  tab_warning$recommand[idx]  <- "judgement"
} else {
  idx <- NULL
}

# cardinally: low cardinality(numerical) ---------------------------------------
warn_unique_num <- diagn_na_unique %>% 
  filter(types %in% c("numeric", "integer")) %>%
  filter(unique_count <= thres_uniq_num & unique_count > 1) %>%
  select(variables, types, unique_count, unique_rate)

if (nrow(warn_unique_num) > 0) {
  idx <- seq(nrow(warn_unique_num)) + idx_last
  
  tab_warning$status[idx]     <- "cardinality"
  tab_warning$variables[idx]  <- warn_unique_num$variables
  tab_warning$types[idx]      <- warn_unique_num$types   
  tab_warning$indicator[idx]  <- warn_unique_num$unique_count
  tab_warning$ratio[idx]      <- warn_unique_num$unique_rate 
  tab_warning$warnings[idx]   <- sprintf(
    "%s has a low cardinality. %s (%s%%) distinct values",
    warn_unique_num$variables, 
    format(warn_unique_num$unique_count, big.mark = ","),
    round(warn_unique_num$unique_rate * 100, 1))  
  tab_warning$recommand[idx]  <- "judgement"
} else {
  idx <- NULL
}

# zeros ------------------------------------------------------------------------
idx_last <- idx_last + length(idx)

warn_zero <- diagn_numeric %>% 
  filter(zero > 0) %>% 
  select(variables, zero) %>% 
  arrange(desc(zero))

if (nrow(warn_zero) > 0) {
  idx <- seq(nrow(warn_zero)) + idx_last
  
  tab_warning$status[idx]     <- "zero"
  tab_warning$variables[idx]  <- warn_zero$variables
  tab_warning$types[idx]      <- NA  
  tab_warning$indicator[idx]  <- warn_zero$zero
  tab_warning$ratio[idx]      <- warn_zero$zero / N 
  tab_warning$warnings[idx]   <- sprintf(
    "%s has %s (%s%%) zeros", warn_zero$variables, 
    format(warn_zero$zero, big.mark = ","), round(warn_zero$zero / N * 100, 2))  
  tab_warning$recommand[idx]  <- "check"
} else {
  idx <- NULL
}

# cardinally: negative ---------------------------------------------------------
idx_last <- idx_last + length(idx)

warn_minus <- diagn_numeric %>% 
  filter(minus > 0) %>% 
  select(variables, minus) %>% 
  arrange(desc(minus))

if (nrow(warn_minus) > 0) {
  idx <- seq(nrow(warn_minus)) + idx_last
  
  tab_warning$status[idx]     <- "negative"
  tab_warning$variables[idx]  <- warn_minus$variables
  tab_warning$types[idx]      <- NA    
  tab_warning$indicator[idx]  <- warn_minus$minus
  tab_warning$ratio[idx]      <- warn_minus$minus / N 
  tab_warning$warnings[idx]   <- sprintf(
    "%s has %s (%s%%) negatives",
    warn_minus$variables, format(warn_minus$minus, big.mark = ","),
    round(warn_minus$minus / N * 100, 2))  
  tab_warning$recommand[idx]  <- "check"
} else {
  idx <- NULL
}

# outlier ----------------------------------------------------------------------
idx_last <- idx_last + length(idx)

warn_outlier <- diagn_numeric %>% 
  filter(outlier > 0) %>% 
  select(variables, outlier) %>% 
  arrange(desc(outlier))

if (nrow(warn_outlier) > 0) {
  idx <- seq(nrow(warn_outlier)) + idx_last
  
  tab_warning$status[idx]     <- "outlier"
  tab_warning$variables[idx]  <- warn_outlier$variables
  tab_warning$types[idx]      <- NA    
  tab_warning$indicator[idx]  <- warn_outlier$outlier
  tab_warning$ratio[idx]      <- warn_outlier$outlier / N 
  tab_warning$warnings[idx]   <- sprintf(
    "%s has %s (%s%%) outliers",
    warn_outlier$variables, format(warn_outlier$outlier, big.mark = ","),
    round(warn_outlier$outlier / N * 100, 2))  
  tab_warning$recommand[idx]  <- "judgement"
} else {
  idx <- NULL
}

tab_warning <- tab_warning %>% 
  filter(status != "")
```

```{r overview, results='asis'}
h1("Overview")
```

```{r overview-datastructure, results='asis'}
h2("Data Structures")
```

```{r overview-pre, results='asis'}
tab_left <- ov[1:9, ]
tab_right <- ov[10:nrow(ov), ]
rownames(tab_right) <- seq(nrow(tab_right))

tab_left <- tab_left %>% 
  mutate(value = ifelse (metrics %in% "memory size", 
                         ifelse(value / 1024^2 > 0, round(value / 1024^2),
                                round(value / 1024)), value)) %>%   
  mutate(metrics = ifelse (metrics %in% "memory size", 
                         ifelse(value / 1024^2 > 0, "memory size (MB)",
                                "memory size (KB)"), metrics))

cap <- "Data Structures"
knitr::kable(tab_left, digits = 2, caption = cap, format = "html",
             format.args = list(big.mark = ","),
             table.attr = "style=\"margin-right:50px !important;\"") %>% 
  kable_styling(full_width = FALSE, font_size = 15, position = "float_left") 

cap <- "Data Types"
knitr::kable(tab_right, digits = 2, caption = cap, format = "html",
             format.args = list(big.mark = ",")) %>% 
  kable_styling(full_width = FALSE, font_size = 15, position = "left") 

breaks <- 9 - nrow(tab_right) + 3
break_line_asis(breaks)
```

```{r overview-warnings, results='asis'}
h2("Warnings")
```

```{r warnings, results='asis'}
tab_warning %>% 
  select(warnings, status, recommand) %>% 
  reactable(
    columns = list(
      warnings = colDef(
        cell = function(value, index) {
          variable_name <- strsplit(value, " ") %>% unlist() %>% "["(1)
          msg <- strsplit(value, " ") %>% unlist() %>% "["(-1) %>% paste(collapse = " ")
          msg <- paste("", msg)
          
          if (tab_warning$status[index] %in% "duplicate") {
            variable <- a(class = "anchor", href = "#ID-duplicate", variable_name)
          } else if (tab_warning$status[index] %in% "missing") {
              variable <- a(class = "anchor", href = "#ID-missing", variable_name)
          } else if (tab_warning$status[index] %in% "cardinality") {
            if (tab_warning$types[index] %in% c("character", "factor", "ordered", 
                                                "Date", "POSIXct"))
              variable <- a(class = "anchor", href = "#ID-unique-cat", variable_name)
            else
              variable <- a(class = "anchor", href = "#ID-unique-num", variable_name)
          } else if (tab_warning$status[index] %in% "outlier") {
              variable <- a(class = "anchor", href = "#ID-outlier", variable_name)            
          } else if (tab_warning$status[index] %in% c("zero", "negative")) {
              variable <- a(class = "anchor", href = "#ID-variables", variable_name)
          } else {
            variable <- div(style = list(color = "red"), variable_name) 
          }

          tagList(
            div(style = list(display = "inline-block"), variable),
            msg
          )
        }
      ),
      status = colDef(name = "types", width = 100),
      recommand = colDef(
        width = 130,
        cell = function(value) {
          class <- paste0("tag recommand-", tolower(value))
          div(class = class, value)
        }
      )  
    )
  )

break_line_asis(2)
```

```{r overview-variables, results='asis'}
h2("Variables", id = "ID-variables")
```

```{r variables, results='asis'}
html_variable(reportData)

break_line_asis(2)
```

```{r missing, results='asis'}
h1("Missing Values")
```

```{r missing-list, results='asis'}
h2("List of Missing Values", id = "ID-missing")
```

```{r missing_data, comment="", results='asis'}
html_missing(diagn_na_unique)

break_line_asis(1)
```

```{r missing-visualization, results='asis'}
h2("Visualization")
```

```{r missing-viz2, dpi=300, fig.height=10, fig.width=10, results='asis'}
diagn_missing <- diagn_na_unique %>% 
  filter(missing_count > 0)

if (NROW(diagn_missing) > 0) {
  break_line_asis(1)
  plot_na_intersect(reportData)
} else {
  html_cat("No variables including missing values")
  break_line_asis(1)
}

break_line_asis(1)
```

```{r unique, results='asis'}
h1("Unique Values")
```

```{r unique-categorical, results='asis'}
h2("Categorical Vaiables", id = "ID-unique-cat")
```

```{r unique_date_category, comment="", results='asis'}
html_unique_cat(diagn_na_unique, thres_uniq_cat)  

break_line_asis(1)
```

```{r unique-numerical, results='asis'}
h2("Numarical Vaiables", id = "ID-unique-num")
```

```{r unique_data_numeric, comment="", results='asis'}
html_unique_num(diagn_na_unique, thres_uniq_num)  

break_line_asis(1)
```

```{r outliers, results='asis'}
h1("Outliers", id = "ID-outlier")
```

```{r outliers-list, comment="", results='asis'}
if (NROW(diagn_numeric) > 0) {
  diagn_outlier <- diagn_numeric %>%
    filter(outlier > 0) 

  if (NROW(diagn_outlier) > 0) {
    cap <- "Diagnosis of numerical variable outliers"
    html_cat(cap)
    
    html_outlier(reportData)
    
  } else {
    html_cat("No numeric variables including outliers")
    break_line_asis(1)
  }
} else {
  html_cat("No numerical variable")
  break_line_asis(1)
}

break_line_asis(1)
```

```{r samples, results='asis'}
h1("Samples")
```

```{r duplicated, results='asis'}
h2("Duplicated", id = "ID-duplicate")
```

```{r duplicated-list, comment="", results='asis'}
cap <- "Duplicated records"
  
idx_dup <- attr(ov, "duplicated")

if (length(idx_dup)) {
  tabs <- reportData[idx_dup, ] %>%
  reactable::reactable(
    defaultColDef = colDef(minWidth = 150)
  )

  htmlwidgets::prependContent(
    tabs, 
    div(class = "caption", style = "padding-top: 8px; padding-bottom: 8px;
        color: #777777; text-align: left;", cap)
  )
} else {
  html_cat("No duplicated records")
  break_line_asis(1)
}

break_line_asis()
```

```{r heades, results='asis'}
h2("Heads")
```

```{r sample-head, comment="", results='asis'}
  cap <- "First few records"
  
tabs <- reportData %>% 
  head(10) %>% 
  reactable::reactable(
    defaultColDef = colDef(minWidth = 150)
  )

htmlwidgets::prependContent(tabs, 
    div(class = "caption", style = "padding-top: 8px; padding-bottom: 8px;
        color: #777777; text-align: left;", cap))

break_line_asis()
```

```{r tails, results='asis'}
h2("Tails")
```

```{r sample-tail, comment=""}
  cap <- "Last few records"
  
tabs <- reportData %>% 
  tail(10) %>% 
  reactable::reactable(
    defaultColDef = colDef(minWidth = 150)
  )

htmlwidgets::prependContent(tabs, 
    div(class = "caption", style = "padding-top: 8px; padding-bottom: 8px;
        color: #777777; text-align: left;", cap))
```

